---
name: Builder
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Build with packer
        run: |
          sudo apt install -y --no-install-recommends packer qemu-system-x86 \
            qemu-utils guestfs-tools genisoimage
              PACKER_LOG=1 packer build mydeb12.json
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: byol_deb12
          path: output/deb12.qcow2
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: output/deb12.qcow2
